language: julia
notifications:
  email: false
julia:
  - 0.6
  - 0.7
  - nightly
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.test("CPUTime")'
